# Autogenerated wrapper script for HandIndexer_jll for aarch64-apple-darwin
export HandIndexer

JLLWrappers.@generate_wrapper_header("HandIndexer")
JLLWrappers.@declare_library_product(HandIndexer, "@rpath/libHandIndexer.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        HandIndexer,
        "lib/libHandIndexer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
