# Autogenerated wrapper script for HandIndexer_jll for x86_64-w64-mingw32
export HandIndexer

JLLWrappers.@generate_wrapper_header("HandIndexer")
JLLWrappers.@declare_library_product(HandIndexer, "libHandIndexer.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        HandIndexer,
        "bin\\libHandIndexer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
